-- Food platform warehouse: foundation objects
-- Run as a role that can create databases (e.g. SYSADMIN).

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS FOOD_ETL_WH
    COMMENT = 'Compute for food-order ELT workloads'
    WAREHOUSE_SIZE = XSMALL
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 120
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE FOOD_ETL_WH;

CREATE DATABASE IF NOT EXISTS FOOD_PLATFORM_DW;
USE DATABASE FOOD_PLATFORM_DW;

CREATE SCHEMA IF NOT EXISTS LANDING;
CREATE SCHEMA IF NOT EXISTS REFINED;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE;

USE SCHEMA LANDING;

CREATE FILE FORMAT IF NOT EXISTS LANDING.FF_CSV_PIPE
    TYPE = CSV
    COMPRESSION = AUTO
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('\\N', 'NULL', '');

CREATE STAGE IF NOT EXISTS LANDING.RAW_FILES_STG
    FILE_FORMAT = LANDING.FF_CSV_PIPE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Upload tutorial CSVs here: initial/ and delta/ subfolders mirror the sample bundle';

USE SCHEMA GOVERNANCE;

CREATE TAG IF NOT EXISTS GOVERNANCE.SENSITIVITY_TAG
    ALLOWED_VALUES 'PII', 'PRICE', 'SENSITIVE', 'EMAIL'
    COMMENT = 'Column-level sensitivity for masking policies';

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_TEXT_PII AS (val STRING)
    RETURNS STRING -> '[PII withheld]';

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_EMAIL AS (val STRING)
    RETURNS STRING -> '[email redacted]';

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_PHONE AS (val STRING)
    RETURNS STRING -> '[phone redacted]';
