--Create intial frame
CREATE DATABASE YOUR_DATABASE;
CREATE SCHEMA YOUR_SCHEMA;

--Switch to our schema
USE DATABASE YOUR_DATABASE;
USE SCHEMA YOUR_SCHEMA;

--Create File Format
CREATE OR REPLACE FILE FORMAT SALES_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '');

SELECT CURRENT_REGION();

--Create Storage integration
CREATE STORAGE INTEGRATION GCS_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = GCS
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('gcs://YOUR_GCS_BUCKET')
    COMMENT = 'Integration fo GCS';

DESC STORAGE INTEGRATION GCS_INT;

--Create notification integration
CREATE NOTIFICATION INTEGRATION GCS_NOTIFY_INT
    TYPE = QUEUE
    ENABLED = TRUE
    NOTIFICATION_PROVIDER = GCP_PUBSUB
    GCP_PUBSUB_SUBSCRIPTION_NAME = 'projects/YOUR_GCP_PROJECT_ID/subscriptions/YOUR_PUBSUB_SUBSCRIPTION'
    COMMENT = 'Notification integration for gcs auto-ingest';

DESC NOTIFICATION INTEGRATION GCS_NOTIFY_INT;

--Create Stage
CREATE OR REPLACE STAGE gcs_stage
  URL = 'gcs://YOUR_GCS_BUCKET'
  STORAGE_INTEGRATION = gcs_int
  FILE_FORMAT = sales_csv_format;

LIST @GCS_STAGE;

--Create raw table
CREATE TABLE SALES_RAW(
    DATE_TEXT STRING,
    SALES_TEXT STRING
);

SELECT * FROM SALES_RAW;

--Create Snowpipe
CREATE PIPE SALES_PIPE
    AUTO_INGEST = TRUE
    INTEGRATION = GCS_NOTIFY_INT
    AS COPY INTO SALES_RAW
    FROM @gcs_stage
    FILE_FORMAT = (FORMAT_NAME = SALES_CSV_FORMAT);

--Create Stream
CREATE STREAM SALES_STREAM
    ON TABLE SALES_RAW;

INSERT INTO SALES_RAW VALUES ('2025-12-06', '3100');

SELECT * FROM SALES_STREAM;

DELETE FROM SALES_RAW
WHERE DATE_TEXT = '2025-12-05';

CREATE TABLE SALES_CLEAN(
    SALE_DATE DATE,
    SALE_AMOUNT NUMBER
);

SELECT * FROM SALES_CLEAN;

CREATE TASK SALES_MERGE_TASK
    WAREHOUSE = YOUR_WAREHOUSE
    SCHEDULE = '1 minute'
AS
    MERGE INTO SALES_CLEAN TGT
    USING (
        SELECT
            CAST(DATE_TEXT AS DATE) AS SALE_DATE,
            CAST(SALES_TEXT AS NUMBER) AS SALE_AMOUNT,
            METADATA$ACTION AS ACTION
        FROM SALES_STREAM
    ) SRC
    ON TGT.SALE_DATE = SRC.SALE_DATE
    WHEN MATCHED AND SRC.ACTION = 'DELETE' THEN
        DELETE
    WHEN MATCHED AND SRC.ACTION = 'UPDATE' THEN
        UPDATE SET TGT.SALE_AMOUNT = SRC.SALE_AMOUNT
    WHEN NOT MATCHED AND SRC.ACTION = 'INSERT' THEN
        INSERT (SALE_DATE, SALE_AMOUNT)
        VALUES(SRC.SALE_DATE, SRC.SALE_AMOUNT);

ALTER TASK SALES_MERGE_TASK RESUME;

SELECT * FROM SALES_CLEAN;

SELECT * FROM SALES_CLEAN_RESTORE;

DELETE FROM SALES_CLEAN
WHERE SALE_DATE = '2025-12-05';

INSERT INTO SALES_CLEAN VALUES ('2025-12-06', '3100');

CREATE TABLE SALES_CLEAN_RESTORE CLONE SALES_CLEAN
BEFORE (STATEMENT => 'YOUR_SNOWFLAKE_QUERY_ID_FOR_TIME_TRAVEL');
